config/routes.rb
Rails.application.routes.draw do
  get 'users/:id', to: 'users#show'

  resources :users, only: [:show] do
    resources :items, shallow: true
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  get 'landing/index'
  root 'landing#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :items
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    authenticated_root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:update, :destroy]
  respond_to :html, :js

  def create
    item = current_user.items.new(item_params)

    if item.save
      render partial: "items/item", locals: { item: item }, status: 200
    else
      render json: { errors: item.errors.full_messages }, status: 400
    end
  end

  def update
    @item.update_attributes(item_params)
  end

  # def show
  #   @user = current_user
  #   @user.item = Item.find(params[:id])
  # end

  def destroy
    @item.destroy
    @items = current_user.items
  end



  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!


  def show
    @user = current_user
    @items = @user.items
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_id
    if current_user.present?
      current_user.id
    else
      nil
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<li data-id="<%= item.id %>"><strong><%= item.name %></strong> &emsp; created <%= distance_of_time_in_words(Time.now, item.created_at) %> ago,
  &ensp; <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %>  remaining
  <!-- <%= link_to edit_item_path(item), remote: true do %>
    <button>Edit</button>
  <% end %> -->
  <%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
</li>

app/views/items/destroy.js.erb
$('#items-list').html("<%= j (render @items) %>");

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knockitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-current-user="<%= current_user_id %>">

  <div class="container">
    <div class="nav nav-tabs">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

    </div>

</body>
</html>

app/views/users/show.html.erb
<div class="container-fluid">

<h2>Welcome back, <%= @user.name %>!</h2><br />
<h4>Your registered email: <strong><%= @user.email %></strong> </h4><br />
<h4>Account created on: <%= @user.created_at.strftime("%m/%d/%Y") %> </h4>

<ul id="items-list">
  <%= render @items %> 
</ul>

<%= form_for [@user, @user.items.new] do |f| %>
  <%= f.text_field :name %>
  <%= link_to "Create Item", 'javascript:;', id: "item-create-btn"%>
<% end %>

</div>